export const pagesRoutes = {
  home: "/",
  login: "/iniciar-sesion",
  signup: "/registro",
  contact: "/contacto",
  cart: "/carrito/:user?",
  profile: "/profile/:user",
  orders: "/:user/orders",
  tickets: "/:user/tickets",
  products: "/productos/:productId",
  calculator: "/pc-calculator",
  deliveryPolicy: "/delivery-policy",
  privatePolicy: "/privacy-policy",
  warrantyPolicy: "/warranty-policy",
};
